config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  resources :google_integrations, only: [:show, :edit, :update, :create] do
    member do
      get :sync
    end
  end

  resources :help_requests

  get '/help' => 'help_requests#new'

  resources :notifications

  resources :account_lists, only: :update

  resources :mail_chimp_accounts do
    collection do
      get :sync
    end
  end

  resources :prayer_letters_accounts do
    collection do
      get :sync
    end
  end

  get "settings/integrations", as: :integrations_settings

  resources :tags, only: [:create, :destroy]

  resources :social_streams, only: :index

  namespace :api do
    api_version(module: 'V1', header: {name: 'API-VERSION', value: 'v1'}, parameter: {name: "version", value: 'v1'}, path: {value: 'v1'}) do
      resources :contacts do
        collection do
          get :count
          get :tags
        end
      end
      resources :tasks do
        collection do
          get :count
        end
      end
      resources :donations, only: [:index]
      resources :preferences
      resources :users
      resources :appeals
    end
    match '*all' => 'v1/base#cors_preflight_check', via: 'OPTIONS'
  end

  resources :imports

  resources :activity_comments

  resources :donations
  resources :accounts
  resources :preferences do
    collection do
      post :update_tab_order
    end
  end

  resources :reports, only: [] do
    collection do
      get :contributions
    end
  end

  resources :contacts do
    collection do
      get :social_search
      put :bulk_update
      delete :bulk_destroy
      post :merge
      get  :find_duplicates
      put :not_duplicates
      post :send_to_chalkline
    end
    member do
      get :add_referrals
      post :save_referrals
      get :details
      get :referrals
    end
    resources :people do
      collection do
        post :merge
      end
    end
  end

  resources :tasks do
    collection do
      get :starred
      get :completed
      get :history
      delete :bulk_destroy
      put :bulk_update
    end
  end

  resources :people do
    collection do
      put :not_duplicates
      post :merge_sets
    end
  end

  resources :research, only: [:index] do
    member do
      get :search
    end
  end

  resources :setup

  namespace :person do
    resources :organization_accounts, only: [:new, :create, :edit, :update, :destroy]
  end

  resource :home, only: [:index], controller: :home do
    get "index"
    get "connect"
    get "care"
    get "cultivate"
    get "progress"
    get "change_account_list"
    get "download_data_check"
  end

  get "privacy" => "home#privacy"
  get "login" => "home#login"

  devise_for :users
  as :user do
    get "/logout" => "sessions#destroy"
  end


  get 'monitors/lb' => 'monitors#lb'

  get '/auth/prayer_letters/callback', to: 'prayer_letters_accounts#create'
  get '/auth/:provider/callback', to: 'accounts#create'
  get '/auth/failure', to: 'accounts#failure'

  developer_user_constraint = lambda { |request| request.env["rack.session"] and
                                  request.env["rack.session"]["warden.user.user.key"] and
                                  request.env["rack.session"]["warden.user.user.key"][0] and
                                  User.find(request.env["rack.session"]["warden.user.user.key"][0].first).developer }
  constraints developer_user_constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/404', :to => "errors#error_404"
  get '/500', :to => "errors#error_500"

  get '/mobile', to: redirect(subdomain: 'm', path: '/')

  mount Peek::Railtie => '/peek'
  root :to => 'home#index'

  get '/templates/:path.html' => 'templates#template', :constraints => { :path => /.+/  }

  # See how all your routes lay out with "rake routes"

end

app/models/user.rb
class User < Person
  has_many :account_list_users, dependent: :destroy
  has_many :account_lists, through: :account_list_users
  has_many :contacts, through: :account_lists
  has_many :account_list_entries, through: :account_lists
  has_many :designation_accounts, through: :account_list_entries
  has_many :donations, through: :designation_accounts
  has_many :designation_profiles, dependent: :destroy
  has_many :partner_companies, through: :account_lists, source: :companies
  has_many :imports, dependent: :destroy

  devise :trackable
  store :preferences, accessors: [:time_zone, :locale, :setup, :contacts_filter,
                                  :tasks_filter, :default_account_list, :contacts_view_options,
                                  :tab_orders, :developer]

  after_create :set_setup_mode

  # Queue data imports
  def queue_imports
    organization_accounts.each do |oa|
      oa.queue_import_data unless oa.last_download
      # oa.queue_import_data unless oa.downloading? || (oa.last_download && oa.last_download > 1.day.ago)
    end
  end

  def tab_order_by_location(location)
    orders = tab_orders || {}
    orders[location] || []
  end

  def merge(other)
    User.transaction do
      other.account_list_users.each do |other_alu|
        other_alu.update_column(:user_id, id) unless account_list_users.find { |alu| alu.account_list_id == other_alu.account_list_id }
      end

      other.designation_profiles.each do |other_dp|
        other_dp.update_column(:user_id, id) unless designation_profiles.find { |dp| dp.code == other_dp.code }
      end

      imports.update_all(user_id: id)
    end

    super
  end

  def setup_mode?
    setup == true || organization_accounts.blank?
  end

  def setup_finished!
    if setup_mode?
      self.setup = nil
      save(validate: false)
    end
  end

  def designation_numbers(organization_id)
    designation_accounts.where(organization_id: organization_id).pluck('designation_number')
  end

  def self.from_omniauth(provider, auth_hash)
    # look for an authenticated record from this provider
    user = provider.find_authenticated_user(auth_hash)
    unless user
      # TODO: hook into IdM to find other identities for this person
      # that might link to an existing user in MPDX

      # Create a new user
      user = provider.create_user_from_auth(auth_hash)
    end
    user
  end

  def self.from_access_token(token)
    User.find_by_access_token(token) ||
    get_user_from_cas_oauth(token)
  end

  def self.get_user_from_cas_oauth(token)
    return nil unless token.present?

    begin
      response = RestClient.get("http://oauth.ccci.us/users/#{token}")
    rescue RestClient::Unauthorized
      return nil
    end

    json = JSON.parse(response.to_str)
    if account = Person::RelayAccount.find_by_remote_id(json['guid'])
      user = account.person.to_user
      user.update_attribute(:access_token, token)
      user
    else
      nil
    end
  end

  def to_person
    Person.find(id)
  end

  private

  def set_setup_mode
    if preferences[:setup].nil?
      preferences[:setup] = true
      save(validate: false)
    end
  end
end

app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < Api::V1::BaseController
  def index
    if params[:since]
      meta = { deleted: Version.where(item_type: 'Activity', event: 'destroy', related_object_type: 'AccountList', related_object_id: current_account_list.id)
                               .where('created_at > ?', Time.at(params[:since].to_i)).pluck(:item_id) }
    else
      meta = {}
    end

    meta.merge!(total: tasks.total_entries, from: correct_from(tasks),
                to: correct_to(tasks), page: page,
                total_pages: total_pages(tasks)) if tasks.respond_to?(:total_entries)

    render json: tasks,
           scope: { since: params[:since] },
           meta:  meta,
           callback: params[:callback]
  end

  def show
    render json: tasks.find(params[:id]), callback: params[:callback]
  end

  def update
    task = tasks.find(params[:id])
    if task.update_attributes(task_params)
      render json: task, callback: params[:callback]
    else
      render json: { errors: task.errors.full_messages }, callback: params[:callback], status: :bad_request
    end
  end

  def create
    task = tasks.new(task_params)
    if task.save
      render json: task, callback: params[:callback], status: :created
    else
      render json: { errors: task.errors.full_messages }, callback: params[:callback], status: :bad_request
    end
  end

  def destroy
    task = tasks.find(params[:id])
    task.destroy
    render json: task, callback: params[:callback]
  end

  # yields {"total": ##,"uncompleted": ##,"overdue": ##}
  def count
    render json: {
      total: tasks.count,
      uncompleted: tasks.uncompleted.count,
      overdue: tasks.overdue.count,
      starred: tasks.uncompleted.starred.count,
      today: tasks.uncompleted.today.count,
      activity_types: tasks.uncompleted.group(:activity_type).count
    },
           callback: params[:callback]
  end

  protected

  def tasks
    filtered_tasks = TaskFilter.new(params[:filters]).filter(current_account_list.tasks)

    add_includes_and_order(filtered_tasks.includes(:contacts, :activity_comments, :people), order: params[:order])
  end

  def task_params
    # this segment is to support App version <= 1.4.1, remove weeks after next release
    if params[:task].present? && params[:task][:contacts_attributes].present? && params[:task][:activity_contacts_attributes].blank?
      params[:task][:activity_contacts_attributes] = params[:task].delete(:contacts_attributes).first
    end
    if params[:task].present? && params[:task][:activity_contacts_attributes].present?
      params[:task][:activity_contacts_attributes].map do |ac|
        ac[:contact_id] = ac.delete(:id) if ac.respond_to?(:each) && ac[:id].present? && ac[:contact_id].blank?
      end
    end

    params.require(:task).permit(Task::PERMITTED_ATTRIBUTES)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :setup_filters, only: :index

  respond_to :html, :js

  def index
    @page_title = _('Tasks')

    @tasks = current_account_list.tasks.uncompleted.includes(:contacts, :activity_comments, :tags)

    @tasks = TaskFilter.new(filters_params).filter(@tasks) if filters_params.present?
    @tasks = @tasks.includes(contacts:
      [
        :referrals_to_me,
        { people: [:phone_numbers, :email_addresses] }
      ]
    )

    @overdue = @tasks.overdue
    @today = @tasks.today
    @tomorrow = @tasks.tomorrow
    @upcoming = @tasks.upcoming
  end

  def starred
    @page_title = _('Starred Tasks')

    @tasks = current_account_list.tasks.uncompleted.starred
  end

  def completed
    @tasks = current_account_list.tasks.completed
  end

  def history
    @page_title = _('Task History')

    @tasks = current_account_list.tasks.completed
                                       .includes(:contacts, :activity_comments, :tags)
                                       .page(page).per_page(per_page)
    filters = filters_params || {}
    filters[:date_range] ||= 'last_week'
    @view_options = params.slice(:per_page, :page)
    @tasks = TaskFilter.new(filters).filter(@tasks)
  end

  # def show
  #   @task = current_account_list.tasks.find(params[:id])
  # end

  def new
    @page_title = _('New Task')

    @task = current_account_list.tasks.new(activity_type: params[:activity_type])
    @old_task = current_account_list.tasks.find_by_id(params[:from]) if params[:from]
    if @old_task
      @task.attributes = @old_task.attributes.select { |k, _v| [:starred, :location, :subject].include?(k.to_sym) }
      @task.tag_list = @old_task.tag_list
      @old_task.activity_contacts.each do |ac|
        @task.activity_contacts.build(contact_id: ac.contact_id)
      end
    end
    if params[:contact_id] && current_user.contacts.exists?(params[:contact_id])
      @task.activity_contacts.build(contact_id: params[:contact_id])
      session[:contact_redirect_to] = contact_path(params[:contact_id], anchor: 'tasks-tab')

      @page_title += _(' For %{contact}').localize % { contact: @task.activity_contacts.first.contact.name } if @task.activity_contacts.length == 1
    end
    if params[:completed]
      @task.completed = true
      session[:contact_redirect_to] = contact_path(params[:contact_id], anchor: 'history-tab') if params[:contact_id]
    end
  end

  def edit
    @task = current_account_list.tasks.find(params[:id])

    @page_title = _('Edit Task - %{task}').localize % { task: @task.subject }

    respond_to do |wants|
      wants.html
      wants.js
    end
  end

  def create
    @task = current_account_list.tasks.new(task_params)

    if params[:add_task_contact_ids].present?
      # First validate the task fields
      if @task.valid?
        # Create a copy of the task for each contact selected
        contacts = current_account_list.contacts.where(id: params[:add_task_contact_ids].split(/[, ]/))
        contacts.each do |c|
          @task = current_account_list.tasks.create(task_params)
          ActivityContact.create(activity_id: @task.id, contact_id: c.id)
        end
      else
        respond_to do |format|
          format.html { render action: 'new' }
          format.js { render action: 'new' }
        end
      end
    else
      respond_to do |format|
        if @task.save
          format.html {
            redirect_to session[:contact_redirect_to] || tasks_path
            session[:contact_redirect_to] = nil
          }
          format.js
        else
          format.html { render action: 'new' }
          format.js { render action: 'new' }
        end
      end
    end
  end

  def update
    @task = current_account_list.tasks.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(task_params)
        format.html { redirect_to tasks_path }
        format.js
      else
        format.html { render action: 'edit' }
        format.js { render action: 'edit' }
      end
    end
  end

  def bulk_update
    tasks = current_account_list.tasks.where(id: params[:bulk_task_update_ids].split(','))
    attributes_to_update = task_params.select { |_, v| v.present? }

    # Set default date values for parts of date that aren't set
    if attributes_to_update['start_at(1i)'] || attributes_to_update['start_at(2i)'] || attributes_to_update['start_at(3i)']
      today = Date.today
      attributes_to_update['start_at(1i)'] ||= today.year.to_s
      attributes_to_update['start_at(2i)'] ||= today.month.to_s
      attributes_to_update['start_at(3i)'] ||= today.day.to_s
    end

    if attributes_to_update.present?
      tasks.map do |t|
        if attributes_to_update['start_at(1i)'] || attributes_to_update['start_at(2i)'] || attributes_to_update['start_at(3i)']
          attributes_with_date = attributes_to_update.dup
          attributes_with_date['start_at(4i)'] ||= t.start_at.hour.to_s
          attributes_with_date['start_at(5i)'] ||= t.start_at.min.to_s
          t.update_attributes(attributes_with_date)
        else
          t.update_attributes(attributes_to_update)
        end
      end
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render text: "document.location = '/tasks'" }
    end
  end

  def bulk_destroy
    current_account_list.tasks.where(id: params[:ids]).destroy_all
    respond_to do |format|
      format.js { render nothing: true }
    end
  end

  def destroy
    @task = current_account_list.tasks.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  private

  def setup_filters
    current_user.tasks_filter ||= {}
    if filters_params.present?
      current_user.tasks_filter[current_account_list.id.to_s] = filters_params
    elsif params[:clear_filter] == 'true'
      current_user.tasks_filter[current_account_list.id.to_s] = nil
    end

    if current_user.tasks_filter.present? && current_user.tasks_filter[current_account_list.id.to_s].present?
      @filters_params = current_user.tasks_filter[current_account_list.id.to_s]
    end
  end

  def task_params
    params.require(:task).permit(Task::PERMITTED_ATTRIBUTES)
  end
end

app/views/tasks/_bulk_modal_form.html.erb
<%= form_for(@task || current_account_list.tasks.new, remote: true) do |f| %>
  <%= hidden_field_tag 'add_task_contact_ids', params[:add_task_contact_ids] %>
  <%= hidden_field_tag 'bulk_task_update_ids', params[:bulk_task_update_ids] %>
  <%= render 'tasks/bulk_fields', task: f.object, f: f %>
<% end %>
<script>
  $('[data-calendar]').datepicker({
    changeYear:true,
    dateFormat: 'yy-mm-dd',
    onSelect: function(dateText) {
      var year = dateText.substr(0,4);
      var month = dateText.substr(5,2);
      var day = dateText.substr(8,2);

      $('.due_date [id$=_1i]').val(year);
      $('.due_date [id$=_2i]').val(month);
      $('.due_date [id$=_3i]').val(day);
    }
  });
</script>

app/views/tasks/_sidebar.html.erb
<aside id="leftmenu">
  <ul>
    <li ng-class="{'selected': filter.page === 'all'}"><a href="/tasks/#" class="inbox menu_item" ng-click="filter.page = 'all'">All</a></li>
    <% if params[:action] == 'index' %>
      <li ng-class="{'selected': filter.page === 'today'}">
        <a href="#" class="inbox menu_item" ng-click="filter.page = 'today'">Today</a>
      </li>
      <li ng-class="{'selected': filter.page === 'overdue'}">
        <a href="#" class="inbox menu_item" ng-click="filter.page = 'overdue'">Overdue</a>
      </li>
      <li ng-class="{'selected': filter.page === 'upcoming'}">
        <a href="#" class="inbox menu_item" ng-click="filter.page = 'upcoming'">Upcoming</a>
      </li>
      <li ng-class="{'selected': filter.page === 'starred'}">
        <a href="#" class="starred menu_item" ng-click="filter.page = 'starred'">Starred</a>
      </li>
    <% end %>
    <li class="<%= 'selected' if params[:action] == 'history' %>"><%= link_to(_('History'), history_tasks_path, class: "completed menu_item") %></li>
    <% if params[:action] == 'index' %>
      <%= render 'sidebar_tags', tags: current_account_list.activity_tags if current_account_list.activity_tags.present? %>
    <% end %>
    <li>
      <span class="left_filters menu_item"><%= _('Filters') %></span>
      <% if params[:action] == 'history' %>
        <form method="get" action="/tasks/history">
      <% end %>
      <% if params[:action] == 'index' %>
        <form>
      <% end %>
        <ul class="left_filters">
          <% if params[:action] == 'history' %>
            <li class="opened">
              <label class="opened"><%= _('Date Range') %></label>
              <div class="collapse">
                <%= radio_button_tag 'filters[date_range]', 'last_week', filters_params[:date_range].blank? || filters_params[:date_range] == 'last_week' %> <%= _('Last Week') %><br />
                <%= radio_button_tag 'filters[date_range]', 'last_month', filters_params[:date_range] == 'last_month'  %> <%= _('Last 31 Days') %><br />
                <%= radio_button_tag 'filters[date_range]', 'last_year', filters_params[:date_range] == 'last_year'  %> <%= _('Last 12 Months') %><br />
                <%= radio_button_tag 'filters[date_range]', 'last_two_years', filters_params[:date_range] == 'last_two_years'  %> <%= _('Last Two Years') %><br />
                <%= radio_button_tag 'filters[date_range]', 'all', filters_params[:date_range] == 'all'  %> <%= _('All') %><br />
              </div>
            </li>
          <% end %>
          <% if params[:action] == 'index' %>
          <li>
            <label><%= _('Action') %></label>
            <div class="collapse" style="display:none;">
              <%= select_tag 'filters[activity_type]', options_for_select([[_('-- Any --'), '']] + (Task.new.assignable_activity_types & current_account_list.tasks.select(:activity_type).uniq.collect(&:activity_type)).collect { |a| [_(a), a] }, filters_params[:activity_type]), multiple: true, size: 5, :'ng-model' => 'filter.actionSelect' %>
            </div>
          </li>
          <li>
            <label id="contact"><%= _('Contact') %></label>
            <div class="collapse" style="display:none;">
              <%= select_tag 'filters[contact_ids]', options_for_select([[_('-- Any --'), '']] + current_account_list.all_contacts.collect { |c| [c.name, c.id] }, filters_params[:contact_ids]), multiple: true, size: 5, :'ng-model' => 'filter.contactsSelect' %>
            </div>
          </li>
          <li>
            <label id="filter_name"><%= _('Contact Name') %></label>
            <div class="collapse" style="display:none;">
              <input ng-model="filter.contactName" type="text">
            </div>
          </li>
          <li>
            <label id="filter_type"><%= _('Contact Type') %></label>
            <div class="collapse" style="display:none;">
              <%= select_tag 'filters[city]', options_for_select([[_('-- Any --'), ''], [_('Person'), 'person'], [_('Company'), 'company']]), multiple: false, size: 5, :'ng-model' => 'filter.contactType' %>
            </div>
          </li>
          <li>
            <label id="filter_city"><%= _('Contact City') %></label>
            <div class="collapse" style="display:none;">
              <%= select_tag 'filters[city]', options_for_select([[_('-- Any --'), '']] + current_account_list.cities.select(&:present?)), multiple: true, size: 5, :'ng-model' => 'filter.contactCity' %>
            </div>
          </li>

          <li>
            <label id="filter_state"><%= _('Contact State') %></label>
            <div class="collapse" style="display:none;">
              <%= select_tag 'filters[state]', options_for_select([[_('-- Any --'), '']] + current_account_list.states.select(&:present?)), multiple: true, size: 5, :'ng-model' => 'filter.contactState' %>
            </div>
          </li>

          <li>
            <label id="filter_newsletter"><%= _('Contact Newsletter') %></label>
            <div class="collapse" style="display:none;">
              <%= radio_button_tag '', '', false, :'ng-model' => 'filter.contactNewsletter' %> <%= _('-- Any --') %><br />
              <%= radio_button_tag '', 'none', false, :'ng-model' => 'filter.contactNewsletter' %> <%= _('None Selected') %><br />
              <%= radio_button_tag '', 'all', false, :'ng-model' => 'filter.contactNewsletter' %> <%= _('All') %><br />
              <div>
                <%= radio_button_tag '', 'address', false, :'ng-model' => 'filter.contactNewsletter' %> <%= _('With Mailing Address') %>
                <%= tip(_('This filter will search for people who are set to receive your physical newsletter and have a mailing address'), style: 'margin: 0 6px -2px') %>
              </div>
              <div>
                <%= radio_button_tag '', 'email', false, :'ng-model' => 'filter.contactNewsletter' %> <%= _('With Email Address') %>
                <%= tip(_('This filter will search for people who are set to receive your email newsletter and have a valid email address'), style: 'margin: 0 6px -2px') %>
              </div>
            </div>
          </li>

          <li>
            <label id="filter_status"><%= _('Contact Status') %></label>
            <div class="collapse" style="display:none;">
              <%= select_tag 'filters[status]', options_for_select([[_('-- Any --'), ''], [_('-- None --'), 'null'], ['Never Contacted', 'Never Contacted'], ['Ask in Future', 'Ask in Future'], ['Contact for Appointment', 'Contact for Appointment'], ['Appointment Scheduled', 'Appointment Scheduled'], ['Call for Decision', 'Call for Decision'], ['Partner - Financial', 'Partner - Financial'], ['Partner - Special', 'Partner - Special'], ['Partner - Pray', 'Partner - Pray'], ['Not Interested', 'Not Interested'], ['Unresponsive', 'Unresponsive'], ['Never Ask', 'Never Ask'], ['Research Abandoned', 'Research Abandoned'], ['Expired Referral', 'Expired Referral']] ), multiple: true, size: 5, :'ng-model' => 'filter.contactStatus' %>
            </div>
          </li>

          <li>
            <label id="filter_likely"><%= _('Contact Likely To Give') %></label>
            <div class="collapse" style="display:none;">
              <%= select_tag '', options_for_select([[_('-- Any --'), ''], ['Least Likely','Least Likely'], ['Likely','Likely'], ['Most Likely','Most Likely']]), multiple: true, size: 4, :'ng-model' => 'filter.contactLikely' %>
            </div>
          </li>

          <li>
            <label id="filter_church"><%= _('Contact Church') %></label>
            <div class="collapse" style="display:none;">
              <%= select_tag 'filters[church]', options_for_select([[_('-- Any --'), '']] + current_account_list.churches.select(&:present?)), multiple: true, size: 5, :'ng-model' => 'filter.contactChurch' %>
            </div>
          </li>

          <li>
            <label id="filter_referrer"><%= _('Contact Referrer') %></label>
            <div class="collapse" style="display:none;">
              <%= select_tag 'filters[referrer]', options_for_select([[_('-- Any --'), ''], [_('-- Someone --'), '*']] + current_account_list.contacts.with_referrals.order("name").collect { |c| [c.name, c.id] }), multiple: true, size: 5, :'ng-model' => 'filter.contactReferrer' %>
            </div>
          </li>
          <li>
            <label id="filter_timezone"><%= _('Contact Timezone') %></label>
            <div class="collapse" style="display:none;">
              <%= select_tag 'filters[timezone]', options_for_select([[_('-- Any --'), '']] + current_account_list.timezones.select(&:present?)), multiple: true, size: 5, :'ng-model' => 'filter.contactTimezone' %>
            </div>
          </li>
          <% end %>
          <li class="controls">
            <% if params[:action] == 'history' %>
              <%= submit_tag _('Apply Filters') %>
            <% else %>
              <a href="#" ng-click="resetFilters()" style="font-size: 11px;">Reset Filters</a>
            <% end %>
          </li>
        </ul>
      </form>
    </li>
  </ul>
</aside>

app/views/tasks/_tasks.html.erb
<table id="tasks_table" class="tablelist tasks">
  <%= render partial: 'tasks/task', collection: tasks %>
</table>

app/views/tasks/history.html.erb
<%= render 'sidebar' %>
<div id="contentbody" class="withleft">
  <div class="wpp">

    <h1></h1>
    <%= render 'pagination', objects: @tasks %>
    <table class="tablelist">
      <thead>
        <tr>
          <th>&nbsp;</th>
          <th><%= _('Contact') %></th>
          <th><%= _('Completed') %></th>
          <th><%= _('Type') %></th>
          <th><%= _('Result') %></th>
          <th><%= _('Action') %></th>
          <th><%= _('Tags') %></th>
          <th><%= _('Subject') %></th>
          <th><%= _('Comments') %></th>
          <th>&nbsp;</th>
        </tr>
      </thead>

      <tbody>
        <% @tasks.each do |task|
          task_exhibit = exhibit(task) %>
          <tr id="<%= dom_id(task) %>">
            <td>
              <input type="checkbox" data-behavior="complete_task" data-id="<%= task.id %>" <%= 'disabled="disabled"' if task.attempted? %> <%= 'checked="checked"' if task.completed? %> />
              <%= form_for task, remote: true, namespace: dom_id(task) do |f| %>
                <%= f.hidden_field :completed, value: false %>
              <% end %>
            </td>
            <td><%= task_exhibit.contact_links %></td>
            <td><%= task_exhibit.completed_at %></td>
            <td><%= _(task_exhibit.activity_type) %></td>
            <td>
              <% if task.attempted? %>
                <%= link_to(_(task_exhibit.result), new_task_path(from: task.id), title: _('Click here to reschedule this task'), class: 'tip') %>
              <% else %>
                <%= _(task_exhibit.result) %>
              <% end %>
            </td>
            <td><%= task_exhibit.next_action %></td>
            <td><%= task_exhibit.tag_list %></td>
            <td><%= task_exhibit %></td>
            <td><%== task.activity_comments.collect(&:body).join('<br />') %></td>
            <td>
              <div class="actions">
                <%= link_to(_('Edit'), edit_task_path(task), :class=> "ico ico_edit") %>
                <%= link_to(_('Delete'), task, data: { confirm: _('Are you sure?') }, method: :delete, :class=> "ico ico_trash") %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="100">
            <%= render 'pagination', objects: @tasks %>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

<%= render 'tasks/results_modal' %>

app/views/tasks/index.js.erb
$('#spinner_tasks').hide();
<% if @tasks.blank? %>
    <% contact = current_account_list.contacts.find(filters_params[:contact_ids]) %>
    $('#tasks').html('<%= j(_("You don't have any outstanding tasks for this contact. ") + link_to(_('Create one now.'), new_task_path(contact_id: contact.id), class: 'add_task', remote: true)) %>');
<% else %>
  <% if params[:page] %>
    $('#tasks_table').append('<%= j(render('tasks/task', collection: @tasks)) %>');
  <% else %>
    $('#tasks').html('<%= j(render('tasks/tasks', tasks: @tasks)) %>');
  <% end %>
<% end %>