config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  resources :google_integrations, only: [:show, :edit, :update, :create] do
    member do
      get :sync
    end
  end

  resources :help_requests

  get '/help' => 'help_requests#new'

  resources :notifications

  resources :account_lists, only: :update

  resources :mail_chimp_accounts do
    collection do
      get :sync
    end
  end

  resources :prayer_letters_accounts do
    collection do
      get :sync
    end
  end

  get "settings/integrations", as: :integrations_settings

  resources :tags, only: [:create, :destroy]

  resources :social_streams, only: :index

  namespace :api do
    api_version(module: 'V1', header: {name: 'API-VERSION', value: 'v1'}, parameter: {name: "version", value: 'v1'}, path: {value: 'v1'}) do
      resources :contacts do
        collection do
          get :count
          get :tags
        end
      end
      resources :tasks do
        collection do
          get :count
        end
      end
      resources :donations, only: [:index]
      resources :preferences
      resources :users
      resources :appeals
    end
    match '*all' => 'v1/base#cors_preflight_check', via: 'OPTIONS'
  end

  resources :imports

  resources :activity_comments

  resources :donations
  resources :accounts
  resources :preferences do
    collection do
      post :update_tab_order
    end
  end

  resources :reports, only: [] do
    collection do
      get :contributions
    end
  end

  resources :contacts do
    collection do
      get :social_search
      put :bulk_update
      delete :bulk_destroy
      post :merge
      get  :find_duplicates
      put :not_duplicates
      post :send_to_chalkline
    end
    member do
      get :add_referrals
      post :save_referrals
      get :details
      get :referrals
    end
    resources :people do
      collection do
        post :merge
      end
    end
  end

  resources :tasks do
    collection do
      get :starred
      get :completed
      get :history
      delete :bulk_destroy
      put :bulk_update
    end
  end

  resources :people do
    collection do
      put :not_duplicates
      post :merge_sets
    end
  end

  resources :research, only: [:index] do
    member do
      get :search
    end
  end

  resources :setup

  namespace :person do
    resources :organization_accounts, only: [:new, :create, :edit, :update, :destroy]
  end

  resource :home, only: [:index], controller: :home do
    get "index"
    get "connect"
    get "care"
    get "cultivate"
    get "progress"
    get "change_account_list"
    get "download_data_check"
  end

  get "privacy" => "home#privacy"
  get "login" => "home#login"

  devise_for :users
  as :user do
    get "/logout" => "sessions#destroy"
  end


  get 'monitors/lb' => 'monitors#lb'

  get '/auth/prayer_letters/callback', to: 'prayer_letters_accounts#create'
  get '/auth/:provider/callback', to: 'accounts#create'
  get '/auth/failure', to: 'accounts#failure'

  developer_user_constraint = lambda { |request| request.env["rack.session"] and
                                  request.env["rack.session"]["warden.user.user.key"] and
                                  request.env["rack.session"]["warden.user.user.key"][0] and
                                  User.find(request.env["rack.session"]["warden.user.user.key"][0].first).developer }
  constraints developer_user_constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/404', :to => "errors#error_404"
  get '/500', :to => "errors#error_500"

  get '/mobile', to: redirect(subdomain: 'm', path: '/')

  mount Peek::Railtie => '/peek'
  root :to => 'home#index'

  get '/templates/:path.html' => 'templates#template', :constraints => { :path => /.+/  }

  # See how all your routes lay out with "rake routes"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_login, only: [:login, :privacy]

  def index
    @page_title = _('Dashboard')
  end

  def connect
    redirect_to '/#dash-connect' && return unless request.xhr?
  end

  def cultivate
    redirect_to '/#dash-cultivate' && return unless request.xhr?
  end

  def care
    redirect_to '/#dash-care' && return unless request.xhr?
  end

  def progress
    redirect_to '/#dash-progress' && return unless request.xhr?

    if params[:start_date]
      @start_date = Date.parse(params[:start_date])
    else
      @start_date = Date.today.beginning_of_week
    end
    @end_date = @start_date.end_of_week

    all_tasks = current_account_list.tasks.completed_between(@start_date, @end_date)

    @counts = {
      phone: {
        completed: all_tasks.of_type('Call')
                            .with_result(%w(Completed Done))
                            .count,
        attempted: all_tasks.of_type('Call')
                            .with_result(['Attempted - Left Message', 'Attempted'])
                            .count,
        received: all_tasks.of_type('Call')
                           .with_result('Received')
                           .count,
        appointments: all_tasks.of_type('Call')
                               .where(next_action: 'Appointment Scheduled')
                               .count
      },
      email: {
        sent: all_tasks.of_type('Email')
                       .with_result(%w(Completed Done))
                       .count,
        received: all_tasks.of_type('Email')
                           .with_result('Received')
                           .count
      },
      facebook: {
        sent: all_tasks.of_type('Facebook Message')
                       .with_result(%w(Completed Done))
                       .count,
        received: all_tasks.of_type('Facebook Message')
                           .with_result('Received')
                           .count
      },
      text_message: {
        sent: all_tasks.of_type('Text Message')
                       .with_result(%w(Completed Done))
                       .count,
        received: all_tasks.of_type('Text Message')
                           .with_result('Received')
                           .count
      },
      electronic: {
        sent: 0,
        received: 0,
        appointments: all_tasks.of_type(['Email', 'Facebook Message', 'Text Message'])
                               .where(next_action: 'Appointment Scheduled')
                               .count
      },
      appointments: {
        completed: all_tasks.of_type('Appointment')
                            .with_result(%w(Completed Done))
                            .count
      },
      correspondence: {
        precall: all_tasks.of_type('Pre Call Letter')
                          .with_result('Done')
                          .count,
        support_letters: all_tasks.of_type('Support Letter')
                                  .with_result('Done')
                                  .count,
        thank_yous: all_tasks.of_type('Thank')
                             .with_result('Done')
                             .count,
        reminders: all_tasks.of_type('Reminder Letter')
                            .with_result('Done')
                            .count
      },
      contacts: {
        active: current_account_list.contacts
                                    .where(status: ['Never Contacted', 'Contact for Appointment', '', nil])
                                    .count,
        referrals: current_account_list.contacts
                                       .created_between(@start_date, @end_date)
                                       .joins(:contact_referrals_to_me).uniq
                                       .count
      }
    }
    @counts[:electronic][:sent] = @counts[:email][:sent] +
                                  @counts[:facebook][:sent] +
                                  @counts[:text_message][:sent]
    @counts[:electronic][:received] = @counts[:email][:received] +
                                  @counts[:facebook][:received] +
                                  @counts[:text_message][:received]
  end

  def login
    render layout: false
  end

  def privacy
    render layout: false
  end

  def change_account_list
    session[:current_account_list_id] = params[:id] if current_user.account_lists.pluck('account_lists.id').include?(params[:id].to_i)
    redirect_to '/'
  end

  def download_data_check
    render text: current_user.organization_accounts.any?(&:downloading?)
  end
end

app/views/home/_care.html.erb
<h2><%= _('Week of %{date1} to %{date2}').localize % {date1: l(Date.today.beginning_of_week), date2: l(Date.today.end_of_week)} %></h2>
<% people_with_birthdays = current_account_list.people_with_birthdays(Time.now.beginning_of_week, Time.now.end_of_week) %>
<% if people_with_birthdays.present? %>
  <h3><%= _('Birthdays') %></h3>
  <ul class="list birthdays">
    <% people_with_birthdays.each do |person|
      person_exhibit = exhibit(person, self) %>
      <li>
        <strong><%= link_to(person_exhibit, person) %></strong>: <%= l(Date.new(Time.now.year, person.birthday_month, person.birthday_day), format: 'MMM-d') %>
        <% if person.primary_phone_number %> - <%= exhibit(person.primary_phone_number) %> <% end %>
        <% if person.primary_email_address %> - <%= mail_to(person.primary_email_address) %> <% end %>
      </li>
    <% end %>
  </ul>
<% end %>
<% people_with_anniversaries = current_account_list.people_with_anniversaries(Time.now.beginning_of_week, Time.now.end_of_week) %>
<% if people_with_anniversaries.present? %>
  <h3><%= _('Anniversaries') %></h3>
  <ul class="list anniversaries">
    <% people_with_anniversaries.each do |person|
      person_exhibit = exhibit(person, self) %>
      <li>
        <strong><%= link_to(person_exhibit, person) %></strong>: <%= l(Date.new(Time.now.year, person.anniversary_month, person.anniversary_day), format: 'MMM-d') %>
        <% if person.primary_phone_number %> - <%= exhibit(person.primary_phone_number) %> <% end %>
        <% if person.primary_email_address %> - <%= mail_to(person.primary_email_address) %> <% end %>
      </li>
    <% end %>
  </ul>
<% end %>
<div>
  <div style="float:left;width:48%">
    <% no_call = current_account_list.no_activity_since(6.months.ago, current_account_list.top_50_percent, 'Call') %>
    <% if no_call.present? %>
      <h3><%= _(' It has been more than 6 months since you have called these important financial partners.') %></h3>
      <table class="list top_50_no_call socstatus">
        <% no_call.collect {|c| exhibit(c, self)}.sort_by(&:to_s).each do |contact| %>
          <tr>
            <td>
              <%= link_to(contact, contact) %>
              &nbsp;&nbsp;
            </td>
            <td><%= link_to(_('Add Task'), new_task_path(contact_id: contact.id, activity_type: 'Call'), class: "add_task", remote: true) %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
  <div style="float:left;width:48%">
    <% no_thank = current_account_list.no_activity_since(1.year.ago, current_account_list.bottom_50_percent, 'Thank') %>
    <% if no_thank.present? %>
      <h3><%= _('It has been more than a year since you have thanked these important financial partners.') %></h3>
      <table class="list top_50_no_call socstatus">
        <% no_thank.collect {|c| exhibit(c, self)}.sort_by(&:to_s).each do |contact| %>
          <tr>
            <td nowrap="nowrap">
              <%= link_to(contact, contact) %>
              &nbsp;&nbsp;
            </td>
            <td>
              <%= link_to(_('Add Task'), new_task_path(contact_id: contact.id, activity_type: 'Thank'), class: "add_task", remote: true) %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>
<div class="clr"></div>
<br />
<h3><%= _('Top Partners') %></h3>
<div id="top5-mp">
  <ul class="list socstatus">
    <% current_account_list.top_partners.each do |contact| %>
      <li>
        <!-- <div class="profile_close"><%= link_to("Close", "Close", :class=> "corner_close") %></div> -->
        <div class="profile_content">
          <%== _('%{link} has given %{total} since %{since}').localize %
                    {link: ('<span class="name">' + link_to(contact.name, contact, :class => "profile_name") + '</span>').html_safe,
                     total: ('<span class="hl amt">' + number_to_current_currency(contact.total_donations) + '</span>').html_safe,
                     since: ('<span class="hl date">' + (contact.first_donation_date ? l(contact.first_donation_date) : '') + '</span>').html_safe } %>
          <p class="desc"></p>
          <!-- <ul class="network_tags list">
            <li><%= link_to("Facebook","#", :class => "icos ico_fb") %></li>
            <li><%= link_to("LinkedIn","#", :class => "icos ico_linkedin") %></li>
            <li><%= link_to("Twitter","#", :class => "icos ico_twitter") %></li>
            <li><%= link_to("Gmail","#", :class => "icos ico_google") %></li>
          </ul> -->
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/home/_connect.html.erb
<% current_account_list.tasks.uncompleted.includes(:contacts).limit(6).tap do |tasks| %>
  <% if tasks.any? %>
    <table class="list tasklist">
      <%= render tasks[0..4] %>
    </table>
  <% else %>
    <%= _("Good news! You don't have any pending tasks.") %>
  <% end %>
  <% if tasks.length > 5 %>
    <div class="seemore">
      <%= link_to(_('See All'), tasks_path) %>
    </div>
  <% end %>
<% end %>

app/views/home/_cultivate.html.erb
<strong><%= _('Last Prayer letter sent:') %></strong>
<% current_account_list.tasks.completed.of_type('Newsletter').first.tap do |newsletter| %>
  <% if newsletter %>
    <%= l(newsletter.completed_at) %>
  <% else %>
    <%= _('Never') %>
  <% end %>
<% end %>

<br /><br />

<%= link_to(_('Contacts still in process:'), contacts_path(filters: {status: Contact::IN_PROGRESS_STATUSES})) %> 
<%= current_account_list.contacts.where(status: Contact::IN_PROGRESS_STATUSES).count %>

<br /><br />

<%= link_to(_('Referrals on hand'), contacts_path(filters: {referrer: '*', status: Contact::IN_PROGRESS_STATUSES})) %>
<%= current_account_list.contacts.joins(:contact_referrals_to_me).where(status: Contact::IN_PROGRESS_STATUSES).where("contact_referrals.id is NOT NULL").count %>

<% late_by_30 = current_account_list.contacts.late_by(31.days, 60.days) %>
<% if late_by_30.length > 0 %>
  <h3><%= _('Partners more than 30 days late') %></h3>
  <ul>
    <% late_by_30.each do |contact| %>
      <% contact_exhibit = exhibit(contact, self) %>
      <li><%= link_to(contact_exhibit, contact) %></li>
    <% end %>
  </ul>
<% end %>

<% late_by_60 = current_account_list.contacts.late_by(60.days) %>
<% if late_by_60.length > 0 %>
  <h3><%= _('Partners more than 60 days late') %></h3>
  <ul>
    <% late_by_60.each do |contact| %>
      <% contact_exhibit = exhibit(contact, self) %>
      <li><%= link_to(contact_exhibit, contact) %></li>
    <% end %>
  </ul>
<% end %>

app/views/home/_donations_summary_chart.html.erb
<%
  first_donation = current_account_list.donations.select('donation_date').last
  if(first_donation)
    first_donation_date = first_donation.donation_date
    @time_span = ((Date.today.end_of_month - first_donation_date).to_f / 30).floor
    @time_span = 12 if @time_span > 12
    @time_span = 1 if @time_span < 1
  else
    @time_span = 1
  end
  @by_month = current_account_list.donations.where("donation_date >= ?", @time_span.months.ago.utc.beginning_of_month).group_by {|r| r.donation_date.beginning_of_month}
   @by_month_index = @time_span.downto(0).collect {|i| i.months.ago.to_date.beginning_of_month}

   pledges = current_account_list.total_pledges.to_i
   total = 0
   @by_month.each { |month| month[1].each { |d| total += d.amount if d.donation_date < Date.today.beginning_of_month } }
   monthly_average = (total / @time_span).to_i
   plot_line_values = [pledges, current_account_list.monthly_goal, monthly_average]
   monthly_values = @by_month_index.collect {|month| @by_month[month] || []}.collect {|v| v.sum(&:amount)} %>


<script type="text/javascript" charset="utf-8">
  var months_to_dates = <%== @time_span.downto(0).collect {|i| i.months.ago.to_date.beginning_of_month}.to_json %>;
  var chart;
  $(document).ready(function() {
    chart = new Highcharts.Chart({
      chart: {
        renderTo: 'donations_summary_chart',
        height: 250
      },
      colors: [
        '#DB843D',
        '#4572A7',
        '#89A54E',
        '#AA4643',
        '#80699B',
        '#3D96AE',
        '#92A8CD',
        '#A47D7C',
        '#B5CA92'
      ],
      title: {
          text: '<span style="color:#007398"><%= j _('Pledges:') %> <%= number_to_current_currency(pledges) %></span> | ' +
                '<span style="color:#3eb1c8"><%= j _('Monthly Goal:') %> <%= number_to_current_currency(current_account_list.monthly_goal) %></span> | ' +
                '<span style="color:#666062"><%= j _('Monthly Average:') %> <%= number_to_current_currency(monthly_average) %></span>',
          useHTML: true,
          style: {
            fontSize: '12px'
          }
      },
      xAxis: {
        categories: [
          <%== @time_span.downto(0).collect {|i| l(i.months.ago.to_date, format: :month_abbrv).inspect}.join(",\n") %>
        ]
      },
      yAxis: {
        min: 0,
        max: <%= (plot_line_values + monthly_values).max * 1.1 %>,
        title: {
          text: '<%= j _('Amount (%{currency})').localize % {currency: current_currency} %>'
        },
        plotLines: [{
          value: <%= pledges %>,
          width: 2,
          color: "#007398"
        },{
          value: <%= current_account_list.monthly_goal %>,
          width: 2,
          color: "#3eb1c8"
        },{
          value: <%= monthly_average %>,
          width: 2,
          color: "#666062"
        }]
      },
      tooltip: {
        formatter: function() {
          var s = '<b>'+ this.x +'</b>';

          $.each(this.points, function(i, point) {
            s += '<br/>'+ point.series.name +': '+
                  point.y +
                  '<br/><%= j _('Percentage of goal') %>: '+
                  Math.round(Number(point.y) / <%= current_account_list.monthly_goal %> * 100) + '%'+
                  '<br/><%= j _('Percentage of average') %>: '+
                  Math.round(Number(point.y) / <%= monthly_average + 0.1 %> * 100) + '%';
          });
          return s;
        },
        shared: true
      },
      plotOptions: {
        column: {
          pointPadding: 0.2,
          borderWidth: 0
        },
        series: {
            cursor: 'pointer',
            events: {
                click: function(event) {
                  document.location = '/donations?start_date=' + months_to_dates[event.point.x]
                }
            }
        }
      },
      series: [{
        name: '<%= _('Donations') %>',
        data: [<%= monthly_values.join(',') %>],
        type: 'column'
      }]
    });
  });
</script>

app/views/home/_progress.html.erb
<div>
  <div style="float:left"><%= link_to(_('<< Previous Week'), progress_home_path(start_date: @start_date - 1.week), remote: true, class: 'no-new-tab') %></div>
  <% unless @end_date >= Date.today %>
    <div style="float:right"><%= link_to(_('Next Week >>'), progress_home_path(start_date: @start_date + 1.week), remote: true, class: 'no-new-tab') %></div>
  <% end %>
</div>
<div class="clr"></div>
<h2><%= _('Week of %{date1} to %{date2}').localize % {date1: l(@start_date.to_date), date2: l(@end_date.to_date)} %></h2>
<% if current_user.organization_accounts.detect {|oa| oa.organization_id == 48} %>
  <%= link_to('Click here to go to the weekly report form for coaches', 'https://staffweb.cru.org/mpd-donations/reports/mpd-weekly-update/index.htm', target: '_blank') %>
  <br /><br />
<% end %>

<div class="progress-category">
  <i class="fa fa-mobile" style="margin-top: -8px; font-size: 7em;"></i>
  <h3><%= _('Phone Dials:') %></h3>
  <span class="progress-category-stat">
    <span><%= @counts[:phone][:completed] + @counts[:phone][:attempted] %></span>
    <%= _('Outgoing Dials') %>
  </span>
  <span class="progress-category-stat">
    <span><%= @counts[:phone][:completed] + @counts[:phone][:received] %></span>
    <%= _('Talked To') %>
  </span>
  <span class="progress-category-stat">
    <span><%= @counts[:phone][:appointments] %></span>
    <%= _('Resulted in Appointments') %>
  </span>
  <ul>
    <li>
      <%= _('Completed:') %>
      <%= @counts[:phone][:completed] %>
    </li>
    <li>
      <%= _('Attempted:') %>
      <%= @counts[:phone][:attempted] %>
    </li>
    <li>
      <%= _('Received:') %>
      <%= @counts[:phone][:received] %>
    </li>
  </ul>
</div>

<div class="progress-category">
  <i class="fa fa-laptop" style="margin-top: -5px;"></i>
  <h3><%= _('Electronic Contacts') %></h3>
  <span class="progress-category-stat">
    <span><%= @counts[:electronic][:sent] %></span>
    <%= _('Sent') %>
  </span>
  <span class="progress-category-stat">
    <span><%= @counts[:electronic][:received] %></span>
    <%= _('Received') %>
  </span>
  <span class="progress-category-stat">
    <span><%= @counts[:electronic][:appointments] %></span>
    <%= _('Resulted in Appointments') %>
  </span>
  <ul>
    <li>
      <%= _('Email:') %>
      <%= @counts[:email][:sent] %>
      <%= _('Sent') %> /
      <%= @counts[:email][:received] %>
      <%= _('Received') %>
    </li>
    <li>
      <%= _('Facebook:') %>
      <%= @counts[:facebook][:sent] %>
      <%= _('Sent') %> /
      <%= @counts[:facebook][:received] %>
      <%= _('Received') %>
    </li>
    <li>
      <%= _('Text Message:') %>
      <%= @counts[:text_message][:sent] %>
      <%= _('Sent') %> /
      <%= @counts[:text_message][:received] %>
      <%= _('Received') %>
    </li>
  </ul>
</div>

<div class="progress-category">
  <i class="fa fa-group" style="margin-top: -2px; font-size: 4.5em;"></i>
  <h3><%= _('Appointments') %></h3>
  <span class="progress-category-stat">
    <span><%= @counts[:appointments][:completed] %></span>
    <%= _('Completed') %>
  </span>
  <ul></ul>
</div>

<div class="progress-category">
  <i class="fa fa-envelope" style="margin-top: -4px;"></i>
  <h3><%= _('Correspondence') %></h3>
  <span class="progress-category-stat">
    <span><%= @counts[:correspondence][:precall] %></span>
    <%= _('Pre-call Letters') %>
  </span>
  <span class="progress-category-stat">
    <span><%= @counts[:correspondence][:support_letters] %></span>
    <%= _('Support Letters') %>
  </span>
  <span class="progress-category-stat">
    <span><%= @counts[:correspondence][:thank_yous] %></span>
    <%= _('Thank You Notes') %>
  </span>
  <span class="progress-category-stat">
    <span><%= @counts[:correspondence][:reminders] %></span>
    <%= _('Reminder Letters') %>
  </span>
</div>

<div class="progress-category">
  <i class="fa fa-child" style="font-size: 6em;"></i>
  <h3><%= _('Contacts') %></h3>
  <span class="progress-category-stat tip" title="<%= _('Always current. Contacts with status: Never Contacted, Contact for Appointment, or none.') %>">
    <span><%= @counts[:contacts][:active] %></span>
    <%= _('Active Contacts') %>
  </span>
  <span class="progress-category-stat">
    <span><%= @counts[:contacts][:referrals] %></span>
    <%= _('Referrals Gained') %>
  </span>
</div>

app/views/home/care.js.erb
$('#dash-care').html('<%= j(render('care')) %>')
if(ga)
  ga('send', 'pageview', '/#care');

app/views/home/connect.js.erb
$('#dash-connect').html('<%= j(render('connect')) %>')
if(ga)
  ga('send', 'pageview', '/#connect');

app/views/home/cultivate.js.erb
$('#dash-cultivate').html('<%= j(render('cultivate')) %>')
if(ga)
  ga('send', 'pageview', '/#cultivate');

app/views/home/index.html.erb
<div id="contentbody">
  <div class="wpp">
    <h1><%= _('Hi') %> <%= current_user.first_name %>! <span class="smallhead"><%= _("Here's whats happening...") %></span></h1>

    <% if current_account_list.monthly_goal.present? %>
      <% cache(['donations_summary_chart', current_account_list], expires_in: 24.hours) do %>
        <div id="donations_summary_chart">

        </div>
        <%= render 'donations_summary_chart' %>
      <% end %>
    <% else %>
      <%= link_to(preferences_path(:focus => "preference_set_monthly_goal")) do %>
        <div class="mwrap">
          <div class="nohide floating info">
            <%= _('Click here to set your monthly goal, after which we will show you a pretty graph of your donations') %>
          </div>
        </div>
      <% end %>
    <% end %>

    <div id="dash-tabs" class="tabgroup">
      <ul>
        <li class="killround"><a href="#dash-connect"><%= _('Connect') %></a></li>
        <li class="killround"><a href="#dash-care"><%= _('Care') %></a></li>
        <li class="killround"><a href="#dash-cultivate"><%= _('Cultivate') %></a></li>
        <li class="killround"><a href="#dash-progress"><%= _('Progress') %></a></li>
        <li class="killround"><a href="#dash-appeals"><%= _('Appeals') %></a></li>
      </ul>

      <div id="dash-connect" ng-controller="taskShortListController" ng-init="init('top5','')">
        <table class="list tasklist">
          <tr task="task" ng-repeat="task in tasks" id="task_{{task.id}}"></tr>
        </table>
        <div class="seemore">
          <%= link_to(_('See All'), tasks_path) %>
        </div>
      </div>
      <div id="dash-care"></div>
      <div id="dash-cultivate"></div>
      <div id="dash-progress"></div>
      <div id="dash-appeals"><p><appeals-list></appeals-list></div>

    </div>

  </div>
</div>
<task-followup-dialog id="task-followup-dialog"></task-followup-dialog>
<%= render 'tasks/results_modal' %>

app/views/home/js.html.erb
<div ng-view></div>

app/views/home/login.html.erb
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>MPDX: Ministry Partner Development Connexion</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "splash", :media => "all" %>
  <%= render 'google_analytics' %>
</head>

<body>
  <% if false %>
    <div class="mwrap">
      <div class="inside notice">
        <p><%= _('Your session has timed out. Please login again.') %></p>
      </div>
    </div>
  <% end %>

  <header>
    <div class="margin pagewidth headercontent">
		  <%= image_tag("splash/logo.png", id: "logo")%>
    </div>
  </header>

  <div id="mainwrap" class="pagewidth margin">
    <div role="main" id="main" class="pagewidth">
      <h1><%= _('Welcome to MPDX!') %></h1>
      <p><%= _('Please choose your preferred <br/> method of logging in:') %></p>

      <div id="login_links">
        <%= link_to(image_tag('splash/relay_logo.png'), '/auth/relay?origin=login', class: "loginlink relay") %>
        <%= link_to(image_tag('splash/key_logo.png'), '/auth/key?origin=login', class: "loginlink relay") %>

      </div>

    </div>
  </div>


  <footer class="margin pagewidth">
    Ministry Partner Development ConneXion | <%= mail_to('support@mpdx.org', _('Support')) %> | <%= link_to(_('Privacy Policy'), '/privacy', target: '_blank') %><br/>&copy; Copyright <%= Time.now.year %> by <%= link_to('Cru', 'http://cru.org') %> <br /><br />
    <a href="https://smartystreets.com ">Address Validation</a> by SmartyStreets
  </footer>

</body>
</html>

app/views/home/progress.js.erb
$('#dash-progress').html('<%= j(render('progress')) %>')
if(ga)
  ga('send', 'pageview', '/#progress');