config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  resources :google_integrations, only: [:show, :edit, :update, :create] do
    member do
      get :sync
    end
  end

  resources :help_requests

  get '/help' => 'help_requests#new'

  resources :notifications

  resources :account_lists, only: :update

  resources :mail_chimp_accounts do
    collection do
      get :sync
    end
  end

  resources :prayer_letters_accounts do
    collection do
      get :sync
    end
  end

  get "settings/integrations", as: :integrations_settings

  resources :tags, only: [:create, :destroy]

  resources :social_streams, only: :index

  namespace :api do
    api_version(module: 'V1', header: {name: 'API-VERSION', value: 'v1'}, parameter: {name: "version", value: 'v1'}, path: {value: 'v1'}) do
      resources :contacts do
        collection do
          get :count
          get :tags
        end
      end
      resources :tasks do
        collection do
          get :count
        end
      end
      resources :donations, only: [:index]
      resources :preferences
      resources :users
      resources :appeals
    end
    match '*all' => 'v1/base#cors_preflight_check', via: 'OPTIONS'
  end

  resources :imports

  resources :activity_comments

  resources :donations
  resources :accounts
  resources :preferences do
    collection do
      post :update_tab_order
    end
  end

  resources :reports, only: [] do
    collection do
      get :contributions
    end
  end

  resources :contacts do
    collection do
      get :social_search
      put :bulk_update
      delete :bulk_destroy
      post :merge
      get  :find_duplicates
      put :not_duplicates
      post :send_to_chalkline
    end
    member do
      get :add_referrals
      post :save_referrals
      get :details
      get :referrals
    end
    resources :people do
      collection do
        post :merge
      end
    end
  end

  resources :tasks do
    collection do
      get :starred
      get :completed
      get :history
      delete :bulk_destroy
      put :bulk_update
    end
  end

  resources :people do
    collection do
      put :not_duplicates
      post :merge_sets
    end
  end

  resources :research, only: [:index] do
    member do
      get :search
    end
  end

  resources :setup

  namespace :person do
    resources :organization_accounts, only: [:new, :create, :edit, :update, :destroy]
  end

  resource :home, only: [:index], controller: :home do
    get "index"
    get "connect"
    get "care"
    get "cultivate"
    get "progress"
    get "change_account_list"
    get "download_data_check"
  end

  get "privacy" => "home#privacy"
  get "login" => "home#login"

  devise_for :users
  as :user do
    get "/logout" => "sessions#destroy"
  end


  get 'monitors/lb' => 'monitors#lb'

  get '/auth/prayer_letters/callback', to: 'prayer_letters_accounts#create'
  get '/auth/:provider/callback', to: 'accounts#create'
  get '/auth/failure', to: 'accounts#failure'

  developer_user_constraint = lambda { |request| request.env["rack.session"] and
                                  request.env["rack.session"]["warden.user.user.key"] and
                                  request.env["rack.session"]["warden.user.user.key"][0] and
                                  User.find(request.env["rack.session"]["warden.user.user.key"][0].first).developer }
  constraints developer_user_constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/404', :to => "errors#error_404"
  get '/500', :to => "errors#error_500"

  get '/mobile', to: redirect(subdomain: 'm', path: '/')

  mount Peek::Railtie => '/peek'
  root :to => 'home#index'

  get '/templates/:path.html' => 'templates#template', :constraints => { :path => /.+/  }

  # See how all your routes lay out with "rake routes"

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :donor_account
  belongs_to :designation_account
  belongs_to :appeal

  validates :amount, :donation_date, presence: true

  # attr_accessible :donor_account_id, :motivation, :payment_method, :tendered_currency, :donation_date, :amount, :tendered_amount, :currency, :channel, :payment_type

  scope :for, -> (designation_account) { where(designation_account_id: designation_account.id) }
  scope :for_accounts, -> (designation_accounts) { where(designation_account_id: designation_accounts.pluck(:id)) }
  scope :since, -> (date) { where('donation_date > ?', date) }

  default_scope { order('donation_date desc') }

  after_create :update_totals
  before_validation :set_amount_from_tendered_amount

  private

  def update_totals
    donor_account.update_donation_totals(self)
    designation_account.update_donation_totals(self) if designation_account
  end

  def set_amount_from_tendered_amount
    if tendered_amount.present?
      self.tendered_amount = tendered_amount_before_type_cast.to_s.gsub(/[^\d\.\-]+/, '').to_f
      self.amount ||= tendered_amount_before_type_cast
    end
  end
end

app/controllers/api/v1/donations_controller.rb
class Api::V1::DonationsController < Api::V1::BaseController
  def index
    order = params[:order] || 'donations.id'

    if params[:contact_id].present?
      donor_account_ids = current_account_list.contacts.find(params[:contact_id]).donor_account_ids
      filtered_donations = current_account_list.donations.where(donor_account_id: donor_account_ids)
    end
    filtered_donations ||= donations

    filtered_donations = add_includes_and_order(filtered_donations, per_page: params[:limit], order: order)
    render json: filtered_donations,
           scope: { user: current_user, account_list: current_account_list, locale: locale },
           callback: params[:callback]
  end

  delegate :donations, to: :current_account_list

  protected

  def available_includes
    [:donor_account]
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :find_donation, only: [:edit, :destroy, :update]
  before_action :find_contact
  before_action :find_donor_accounts, only: [:edit, :new]
  before_action :find_appeals, only: [:index, :edit, :new]

  def index
    if @contact
      if @contact.donor_account_ids.present?
        @all_donations = current_account_list.donations.where(donor_account_id: @contact.donor_account_ids)
      else
        # If the contact isn't linked to a donor account, they're not going to have any donations.
        @all_donations = Donation.where('1 <> 1')
      end
      @donations = @all_donations.page(params[:page])
      setup_chart unless params[:page]
    else
      @page_title = _('Donations')

      if params[:start_date]
        @start_date = Date.parse(params[:start_date])
      else
        @start_date = Date.today.beginning_of_month
      end
      @end_date = @start_date.end_of_month
      @donations = current_account_list.donations.where('donation_date BETWEEN ? AND ?', @start_date, @end_date)
                                                 .where('contacts.account_list_id' => current_account_list.id)
                                                 .includes(donor_account: :contacts)
    end
  end

  def edit
  end

  def new
    redirect_to donations_path && return unless request.xhr?

    @donation = current_account_list.donations.new(designation_account_id: current_account_list.designation_accounts.first.try(:id))
  end

  def create
    @donation = current_account_list.donations.new(donation_params)

    return if @donation.save
    find_donor_accounts
    render action: :new
  end

  def update
    return if @donation.update_attributes(donation_params)
    find_donor_accounts
    render action: :edit
  end

  def destroy
    @donation.destroy
  end

  private

  def setup_chart
    @by_month = @all_donations.where('donation_date >= ?', 12.months.ago.beginning_of_month).group_by { |r| r.donation_date.beginning_of_month }
    @by_month_index = 12.downto(0).map { |i| i.months.ago.to_date.beginning_of_month }
    @prior_year = @all_donations.where('donation_date >= ? AND donation_date < ?', 24.months.ago.beginning_of_month, 11.months.ago.beginning_of_month)
                                .group_by { |r| r.donation_date.beginning_of_month }
    @prior_year_index = 24.downto(12).map { |i| i.months.ago.to_date.beginning_of_month }
  end

  def find_donation
    @donation = current_account_list.donations.find(params[:id])
  end

  def donation_params
    params.require(:donation).permit('donation_date(1i)', 'donation_date(2i)',
                                     'donation_date(3i)', 'tendered_amount',
                                     'donor_account_id', 'designation_account_id',
                                     'appeal_id', 'appeal_amount')
  end

  def find_contact
    @contact = current_account_list.contacts.where(id: params[:contact_id]).first if params[:contact_id]
  end

  def find_appeals
    @appeals = current_account_list.appeals
  end

  def find_donor_accounts
    @donor_accounts = []
    if @contact
      @contact.donor_accounts.each do |da|
        @donor_accounts << ["#{@contact.name} (#{da.account_number})", da.id]
      end
    else
      current_account_list.contacts.active.joins(:donor_accounts).includes(:donor_accounts).each do |c|
        c.donor_accounts.each do |da|
          @donor_accounts << ["#{c.name} (#{da.account_number})", da.id]
        end
      end
      @donor_accounts.sort_by!(&:first)
    end
  end
end

app/views/donations/_chart.html.erb
<% @contact = exhibit(@contact, self) %>
<%#<div class="donation-filters">%>
  <%#<form>%>
    <%#<select>%>
      <%#<option>Designation<option>%>
      <%#<option>-----------------------</option>%>
      <%#<option>1123456722 [Cru]</option>%>
      <%#<option>112342155 [Summer Project]</option>%>
    <%#</select>%>
    <%#<select>%>
      <%#<option>Appeal<option>%>
      <%#<option>-----------------------</option>%>
      <%#<option>Dinner</option>%>
      <%#<option>Christmas Gift</option>%>
    <%#</select>%>
  <%#</form>%>
<%#</div>%>

<% if @by_month.present? %>
  <% average =  (@by_month.values.collect {|v| v.sum(&:amount)}.reverse[0..11].sum / 12).round %>
  <% prior_average =  (@prior_year.values.collect {|v| v.sum(&:amount)}.reverse[0..11].sum / 12).round %>

  <div class="donation-charts" id="donation_chart">
    <%= _('No donations have been received from %{contact} in the past 13 months').localize % { contact: @contact || 'this person' } %>
  </div>

  <script type="text/javascript" charset="utf-8">
    var chart;
    $(document).ready(function() {
      chart = new Highcharts.Chart({
        chart: {
          renderTo: 'donation_chart',
          height: 250
        },
        colors: [
          '#DB843D',
          '#4572A7',
          '#89A54E',
          '#AA4643',
          '#80699B',
          '#3D96AE',
          '#92A8CD',
          '#A47D7C',
          '#B5CA92'
        ],
        title: {
          text: '<%= j _('Donation History') %>'
        },
        subtitle: {
          text: '<%== j(if prior_average > average
                        _('Average donations down <span style="color:red">%{amount}</span> from last year').localize % { amount: number_to_current_currency(prior_average - average) }
                     elsif average > prior_average
                       _('Average donations up <span style="color:green">%{amount}</span> from last year').localize % { amount: number_to_current_currency(average - prior_average) }
                     else
                       ''
                      end) %>'
        },
        xAxis: {
          categories: [
          <%== 12.downto(0).collect {|i| l(i.months.ago.to_date, format: :month_abbrv).inspect}.join(",\n") %>
          ]
        },
        yAxis: {
          min: 0,
          title: {
            text: '<%= j _('Amount (USD)') %>'
          }
        },
        tooltip: {
          formatter: function() {
            return this.y;
          }
        },
        plotOptions: {
          column: {
            pointPadding: 0.2,
            borderWidth: 0
          }
        },
        series: [{
          name: '<%= j _('Donations') %>',
          data: [<%= @by_month_index.collect {|month| @by_month[month] || []}.collect {|v| v.sum(&:amount)}.join(',') %>],
          type: 'column'
        },{
          name: '<%= j _('Last Year') %>',
          data: [<%= @prior_year_index.collect {|month| @prior_year[month] || []}.collect {|v| v.sum(&:amount)}.join(',') %>],
          type: 'column'
        },{
  name: '<%= j _('Average') %>',
        data: [<%= 0.upto(12).collect {|i| average}.join(',') %>],
          type: 'line'
        }]
      });
    });
  </script>
<% end %>

app/views/donations/_donation.html.erb
<% exhibit(donation, self).tap do |donation_exhibit| %>
<tr id="<%= dom_id(donation) %>">
  <% if @contact %>
    <td><%= donation.donor_account.name %></td>
  <% end %>
  <td class="date"><%= l donation_exhibit.donation_date %></td>
  <% unless @contact %>
    <td><%= link_to(donation.donor_account.contacts.first.name, donation.donor_account.contacts.first) %></td>
  <% end %>
  <td class="right"><%= donation_exhibit.tendered_amount %></td>
  <% if current_account_list.multiple_designations %>
    <td><%= donation.designation_account.designation_number %></td>
  <% end %>
  <td><%= donation_exhibit.payment_method %></td>
  <td><%= donation_exhibit.motivation %></td>
  <%#<td class="appeal">Dinner</td>%>
  <td><%= link_to('<i class="fa fa-pencil-square-o"></i>'.html_safe, edit_donation_path(donation, contact_id: @contact.try(:id)), remote: true, class: 'no-new-tab') %></td>
</tr>
<% end %>

app/views/donations/_donations.html.erb
<% @contact = exhibit(@contact, self) if @contact %>
<% unless params[:page] %>
  <% if @start_date %>
    <div class="filters">
      <div style="float:left"><%= link_to(_('<< Previous Month'), donations_path(start_date: @start_date - 1.month), class: 'btn smallbtn') %></div>
      <div style="float:right"><%= link_to(_('Contribution Report'), contributions_reports_path, class: 'btn smallbtn') %></div>
      <% unless @end_date >= Date.today %>
        <div style="float:right"><%= link_to(_('Next Month >>'), donations_path(start_date: @start_date + 1.month), class: 'btn smallbtn') %>&nbsp;|&nbsp;</div>
      <% end %>

    </div>
    <div class="clr"></div>
    <h2><%= _('Donations for %{start_date} through %{end_date}').localize % {start_date: l(@start_date), end_date: l(@end_date)} %></h2>
    <%= link_to('<i class="fa fa-plus-square"></i> '.html_safe + _('Add a donation'), new_donation_path, remote: true, class: 'no-new-tab') %>
    <br /><br />
  <% end %>
<table class="tablelist donations" id="donations_table">
  <thead>
    <tr>
      <% if @contact %>
        <th>Donor</th>
      <% end %>
      <th class="date">Date</th>
      <% unless @contact %>
        <th>Donor</th>
      <% end %>
      <th class="right">Amount</th>
      <% if current_account_list.multiple_designations %>
        <th>Designation</th>
      <% end %>
      <th><%= _('Method') %></th>
      <th><%= _('Motivation') %></th>
      <%#<th class="appeal">Appeal</th>%>
      <th></th>
    </tr>
  </thead>
  <tbody>
<% end %>

<%= render donations %>

<% unless params[:page] %>
  </tbody>
  <% unless @contact %>
    <tfoot>
      <tr class="sum">
        <td></td>
        <td class="right"><strong><%= _('Total Donations (%{count}):').localize % {count: donations.length} %></strong></td>
        <td class="right"><%= number_to_current_currency(donations.to_a.sum(&:amount)) %></td>
        <td colspan="4"></td>
      </tr>
    </tfoot>
  <% end %>
</table>
<% end %>

<div id="js-edit_donation" style="display:none" title="<%= _('Edit Donation') %>">
  <%= spinner(extra: 'edit-donation') %>
  <div class="form_wrapper"></div>
</div>

app/views/donations/_form.html.erb
<% if @donor_accounts.present? %>
  <%= form_for donation, remote: true do |f| %>
    <%= hidden_field_tag :contact_id, params[:contact_id] %>
    <% if donation.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% donation.errors.each do |attribute, error| %>
            <% next if attribute.to_s.include?('.') %>
            <li><%= donation.errors.full_message(attribute, error) %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :donation_date, _('Date') %>
      <%= f.date_select :donation_date %>
    </div>

    <div class="field">
      <%= f.label :tendered_amount, _('Amount') %>
      <%= f.text_field :tendered_amount %>
    </div>

    <% if @donor_accounts.length > 1 %>
      <div class="field">
        <%= f.label :donor_account_id, _('Donor') %>
        <%= f.select :donor_account_id, @donor_accounts %>
      </div>
    <% else %>
      <%= f.hidden_field :donor_account_id, value: @donor_accounts.first[1] %>
    <% end %>

    <div class="field">
      <%= f.label :appeal_id, _('Appeal') %>
      <%= f.select :appeal_id, options_from_collection_for_select(@appeals, 'id', 'name', donation.appeal.present? ? donation.appeal.id : ''),
                   :include_blank => true %>
    </div>

    <div class="field">
      <%= f.label :appeal_amount, _('Appeal Amount') %>
      <%= f.text_field :appeal_amount %>
      <br>Leave empty to use full donation amount
    </div>

    <% if current_account_list.multiple_designations %>
      <div class="field">
        <%= f.label :designation_account_id, _('Designation Account') %>
        <%= f.select :designation_account_id, current_account_list.designation_accounts.collect {|da| [da.designation_number, da.id]} %>
      </div>
    <% else %>
      <%= f.hidden_field :designation_account_id %>
    <% end %>


    <% unless donation.new_record? %>
      <div class="field">
        <%= link_to(_('Click here to delete this donation'), donation_path(donation), method: :delete, class: 'red delete_donation', data: { confirm: _('Are you sure?') }, remote: true) %>
      </div>
    <% end %>

  <% end %>
<% else %>
  <%= _('None of your contacts are associated with donor accounts. Please edit a contact and give them a Donor Account before trying to add a donation.') %>
<% end %>

app/views/donations/contribution_report.html.erb
<% if @start_date %>
  <div class="filters">
    <div style="float:left"><%= link_to(_('<< Previous Year'), contribution_report_donations_path(start_date: @start_date - 1.year), class: 'btn smallbtn') %></div>
    <div style="float:right"><%= link_to(_('Donations'), donations_path, class: 'btn smallbtn') %></div>
    <% unless @end_date >= Date.today %>
      <div style="float:right"><%= link_to(_('Next Year >>'), contribution_report_donations_path(start_date: @start_date + 1.year), class: 'btn smallbtn') %>&nbsp;|&nbsp;</div>
    <% end %>

  </div>
  <div class="clr"></div>
  <h2><%= _('Contribution Report for %{start_date} through %{end_date}').localize % {start_date: l(@start_date), end_date: l(@end_date)} %></h2>
<% end %>
<table class="tablelist donations" id="donations_table">
  <thead>
    <tr>
      <th>Donor</th>
      <th></th>
      <% (0..11).reverse_each do |index| %>
        <th class="right"><%= index.month.ago(@end_date).strftime '%b %y' %></th>
      <% end %>
      <th class="total right">Total</th>
    </tr>
  </thead>
  <tbody>
    <% @donations.each do |key, row| %>
      <tr>
        <td><%= link_to(row[:donor].contacts.first.name, row[:donor].contacts.first) %><td>
        <% (0..11).reverse_each do |index| %>
          <td class="right">
            <% unless row[:amounts][index.month.ago(@end_date).strftime '%b %y'].nil? %>
              <%= number_to_current_currency(row[:amounts][index.month.ago(@end_date).strftime '%b %y']) %>
            <% end %>
          </td>
        <% end %>
        <td class="total right"><%= number_to_current_currency(row[:total]) %></td>
      </tr>
    <% end %>
    <tr class="sum">
      <td><strong>Total Donations</strong></td><td></td>
      <% (0..11).reverse_each do |index| %>
        <td class="right">
          <% unless @sum_row[index.month.ago(@end_date).strftime '%b %y'].nil? %>
            <%= number_to_current_currency(@sum_row[index.month.ago(@end_date).strftime '%b %y']) %>
          <% end %>
        </td>
      <% end %>
      <td class="total"></td>
    </tr>
  </tbody>
</table>

app/views/donations/create.js.erb
$('#donations_table').prepend('<%= j(render @donation) %>')

app/views/donations/destroy.js.erb
$('#<%= dom_id(@donation) %>').fadeOut()

app/views/donations/edit.js.erb
$('.form_wrapper').html('<%= j(render('form', donation: @donation)) %>')
$('#js-edit_donation').dialog({
  buttons: [
    {
      text: __('Save'),
      click: function(e) {
        $('form', this).trigger('submit')
      }
    }, {
      text: __('Cancel'),
      click: function() {
        $(this).dialog("destroy");
      }
    }
  ]
});

app/views/donations/index.html.erb
<%= render('donations', donations: @donations) %>

app/views/donations/index.js.erb
$('#spinner_donations').hide();
<% if params[:page] %>
  $('#donations_table').append('<%= j(render('donations', donations: @donations)) %>');
<% else %>
  $('#donations').html('<%= j(render('chart', donations: @donations)) %>');
  $('#donations').append('<%= j(render('donations', donations: @donations)) %>');
<% end %>
if($('.pagination')[0]) {
  $('.pagination').remove()
}
<% if @donations.respond_to?(:next_page) && @donations.next_page %>
  $('#donations').append('<%= j(will_paginate @donations, remote: true, page_links: false, previous_label: '', next_label: 'More') %>')
<% end %>

app/views/donations/new.js.erb
$('.form_wrapper').html('<%= j(render('form', donation: @donation)) %>')
$('#js-edit_donation').dialog({
  title: __('New Donation'),
  width: 'auto',
  buttons: [
    {
      text: __('Save'),
      click: function(e) {
        $('form', this).trigger('submit')
      }
    }, {
      text: __('Cancel'),
      click: function() {
        $(this).dialog("destroy");
      }
    }
  ]
});

app/views/donations/update.js.erb
$('#<%= dom_id(@donation) %>').replaceWith('<%= j(render @donation) %>')