config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  resources :google_integrations, only: [:show, :edit, :update, :create] do
    member do
      get :sync
    end
  end

  resources :help_requests

  get '/help' => 'help_requests#new'

  resources :notifications

  resources :account_lists, only: :update

  resources :mail_chimp_accounts do
    collection do
      get :sync
    end
  end

  resources :prayer_letters_accounts do
    collection do
      get :sync
    end
  end

  get "settings/integrations", as: :integrations_settings

  resources :tags, only: [:create, :destroy]

  resources :social_streams, only: :index

  namespace :api do
    api_version(module: 'V1', header: {name: 'API-VERSION', value: 'v1'}, parameter: {name: "version", value: 'v1'}, path: {value: 'v1'}) do
      resources :contacts do
        collection do
          get :count
          get :tags
        end
      end
      resources :tasks do
        collection do
          get :count
        end
      end
      resources :donations, only: [:index]
      resources :preferences
      resources :users
      resources :appeals
    end
    match '*all' => 'v1/base#cors_preflight_check', via: 'OPTIONS'
  end

  resources :imports

  resources :activity_comments

  resources :donations
  resources :accounts
  resources :preferences do
    collection do
      post :update_tab_order
    end
  end

  resources :reports, only: [] do
    collection do
      get :contributions
    end
  end

  resources :contacts do
    collection do
      get :social_search
      put :bulk_update
      delete :bulk_destroy
      post :merge
      get  :find_duplicates
      put :not_duplicates
      post :send_to_chalkline
    end
    member do
      get :add_referrals
      post :save_referrals
      get :details
      get :referrals
    end
    resources :people do
      collection do
        post :merge
      end
    end
  end

  resources :tasks do
    collection do
      get :starred
      get :completed
      get :history
      delete :bulk_destroy
      put :bulk_update
    end
  end

  resources :people do
    collection do
      put :not_duplicates
      post :merge_sets
    end
  end

  resources :research, only: [:index] do
    member do
      get :search
    end
  end

  resources :setup

  namespace :person do
    resources :organization_accounts, only: [:new, :create, :edit, :update, :destroy]
  end

  resource :home, only: [:index], controller: :home do
    get "index"
    get "connect"
    get "care"
    get "cultivate"
    get "progress"
    get "change_account_list"
    get "download_data_check"
  end

  get "privacy" => "home#privacy"
  get "login" => "home#login"

  devise_for :users
  as :user do
    get "/logout" => "sessions#destroy"
  end


  get 'monitors/lb' => 'monitors#lb'

  get '/auth/prayer_letters/callback', to: 'prayer_letters_accounts#create'
  get '/auth/:provider/callback', to: 'accounts#create'
  get '/auth/failure', to: 'accounts#failure'

  developer_user_constraint = lambda { |request| request.env["rack.session"] and
                                  request.env["rack.session"]["warden.user.user.key"] and
                                  request.env["rack.session"]["warden.user.user.key"][0] and
                                  User.find(request.env["rack.session"]["warden.user.user.key"][0].first).developer }
  constraints developer_user_constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/404', :to => "errors#error_404"
  get '/500', :to => "errors#error_500"

  get '/mobile', to: redirect(subdomain: 'm', path: '/')

  mount Peek::Railtie => '/peek'
  root :to => 'home#index'

  get '/templates/:path.html' => 'templates#template', :constraints => { :path => /.+/  }

  # See how all your routes lay out with "rake routes"

end

app/controllers/reports_controller.rb
require 'csv_util'

class ReportsController < ApplicationController
  def contributions
    @page_title = _('Contribution Report')

    if params[:start_date]
      @start_date = Date.parse(params[:start_date])
      @end_date = @start_date.end_of_month + 11.months
    else
      @end_date = Date.today.end_of_month
      @start_date = 11.month.ago(@end_date).beginning_of_month
    end

    # The reason for the "distinct_contact_donor_accounts" inner query is that it's possible
    # due to a TntMPD import that two different contacts could both be assigned the same donor id
    # which would cause duplicated results in the sum columns of the report.
    @raw_donations = current_account_list
      .donations
      .where('donation_date BETWEEN ? AND ?', @start_date, @end_date)
      .select('"donations"."donor_account_id",' \
              'date_trunc(\'month\', "donations"."donation_date"),' \
              'SUM("donations"."tendered_amount") as tendered_amount,' \
              '"donations"."tendered_currency",' \
              '"donor_accounts"."name",' \
              '"distinct_contact_donor_accounts"."contact_id" as contact_id,' \
              '"contacts"."status",'\
              '"contacts"."pledge_amount",' \
              '"contacts"."pledge_frequency"'
      )
      .where('contacts.account_list_id' => current_account_list.id)
      .joins('INNER JOIN donor_accounts ON donor_accounts.id = donations.donor_account_id')
      .joins('INNER JOIN ' \
               '(SELECT donor_account_id, MIN(contact_id) as contact_id' \
               ' FROM contact_donor_accounts ' \
               ' INNER JOIN contacts ON contacts.id = contact_donor_accounts.contact_id ' \
               " WHERE contacts.account_list_id = #{current_account_list.id.to_i}" \
               ' GROUP BY donor_account_id) ' \
               'distinct_contact_donor_accounts ' \
              'ON distinct_contact_donor_accounts.donor_account_id = donations.donor_account_id')
      .joins('INNER JOIN contacts ON contacts.id = distinct_contact_donor_accounts.contact_id')
      .group('donations.donor_account_id, ' \
             'date_trunc, ' \
             'tendered_currency, ' \
             'donor_accounts.name, ' \
             'distinct_contact_donor_accounts.contact_id, ' \
             'status, ' \
             'pledge_amount, ' \
             'pledge_frequency '
             )
      .reorder('donor_accounts.name')
      .distinct
      .to_a
    @donations = {}
    @sum_row = {}
    @raw_donations.each do |donation|
      @donations[donation.donor_account_id] ||= {
        donor: donation.name, id: donation.contact_id, status: donation.status,
        pledge_amount: donation.pledge_amount,
        pledge_frequency: donation.pledge_frequency,
        amounts: {}, total: 0
      }

      @donations[donation.donor_account_id][:amounts][donation.date_trunc.strftime '%b %y'] = {
        value: donation.tendered_amount,
        currency: donation.tendered_currency
      }

      @donations[donation.donor_account_id][:total] += donation.tendered_amount

      @sum_row[donation.date_trunc.strftime '%b %y'] ||= 0

      @sum_row[donation.date_trunc.strftime '%b %y'] += donation.tendered_amount
    end

    @total_pledges = 0.0
    @total_average = 0.0
    @donations.each do |_key, row|
      if !row[:pledge_amount].nil? && !row[:pledge_frequency].nil?
        @total_pledges += row[:pledge_amount] / row[:pledge_frequency]
      end

      if !row[:pledge_frequency].nil? && row[:pledge_frequency].to_f <= 1.0
        # If someone gives monthly and they gave, e.g. $50/month for the past four month
        # and not before that, then assume they are a new ministry partner and their average
        # should be $50/month.
        # Thus we find the first month in the report (from left to right) where they
        # gave a donation and exclude earlier months from the average.
        month_of_first_donation = (0..11).to_a.reverse.find_index {|index|
          !row[:amounts][index.month.ago(@end_date).strftime '%b %y'].nil?
        }
        months_for_average = 12.0 - month_of_first_donation

        # If there was no donation in the current month, then don't count the current
        # month toward the average calculation, as it may be midway through the month
        # and their donation hasn't shown up yet.
        if row[:amounts][0.month.ago(@end_date).strftime '%b %y'].nil?
          months_for_average -= 1.0
        end
      else
        months_for_average = 12.0
      end

      row[:average] = row[:total] / months_for_average
      @total_average += row[:average]
    end

    respond_to do |format|
      format.html
      format.csv do
        html_table = render_to_string formats: [:html], layout: false
        render text: CSVUtil.html_table_to_csv(html_table)
      end
    end
  end
end

app/views/reports/contributions.html.erb
<% if @start_date %>
  <div class="filters">
    <div style="float:left"><%= link_to(_('<< Previous Year'), contributions_reports_path(start_date: @start_date - 1.year), class: 'btn smallbtn') %></div>
    <div style="float:right"><%= link_to(_('Donations'), donations_path, class: 'btn smallbtn') %></div>
    <% unless @end_date >= Date.today %>
      <div style="float:right"><%= link_to(_('Next Year >>'), contributions_reports_path(start_date: @start_date + 1.year), class: 'btn smallbtn') %>&nbsp;|&nbsp;</div>
    <% end %>

  </div>
  <div class="clr"></div>
  <h2><%= _('Contribution Report for %{start_date} through %{end_date}').localize % {start_date: l(@start_date), end_date: l(@end_date)} %></h2>
  <%= link_to _('Download as CSV spreadsheet file'), request.parameters.merge({ format: 'csv' }) %>
<% end %>
<table class="tablelist donations" id="donations_table">
  <thead>
    <tr>
      <th><%= _('Donor') %></th>
      <th><%= _('Status') %></th>
      <th><%= _('Pledge Amount') %></th>
      <th><%= _('Pledge Frequency') %></th>
      <th><%= _('Average') %></th>
      <% (0..11).reverse_each do |index| %>
        <th class="right"><%= index.month.ago(@end_date).strftime '%b %y' %></th>
      <% end %>
      <th class="total right"><%= _('Total') %></th>
    </tr>
  </thead>
  <tbody>
    <% @donations.each do |key, row| %>
      <tr>
        <td><%= link_to(row[:donor], contact_path(row[:id])) %></td>
        <td><%= row[:status] %></td>
        <td><%= number_to_current_currency(row[:pledge_amount]) %></td>
        <td><%= Contact.pledge_frequencies[row[:pledge_frequency]] %></td>
        <td><%= number_to_current_currency(row[:average], precision: 2) %></td>
        <% (0..11).reverse_each do |index| %>
          <td class="right">
            <% unless row[:amounts][index.month.ago(@end_date).strftime '%b %y'].nil? %>
              <%= number_to_current_currency(row[:amounts][index.month.ago(@end_date).strftime '%b %y'][:value], currency: row[:amounts][index.month.ago(@end_date).strftime '%b %y'][:currency]) %>
            <% end %>
          </td>
        <% end %>
        <td class="total right"><%= number_to_current_currency(row[:total]) %></td>
      </tr>
    <% end %>
    <tr class="sum">
      <td><strong><%= _('Total Donations') %></strong></td>
      <td></td>
      <td><%= number_to_current_currency(@total_pledges) %></td>
      <td></td>
      <td><%= number_to_current_currency(@total_average) %></td>
      <% (0..11).reverse_each do |index| %>
        <td class="right">
          <% unless @sum_row[index.month.ago(@end_date).strftime '%b %y'].nil? %>
            <%= number_to_current_currency(@sum_row[index.month.ago(@end_date).strftime '%b %y']) %>
          <% end %>
        </td>
      <% end %>
      <td class="total"></td>
    </tr>
  </tbody>
</table>